spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: true
      uri: http://config-server:8071
  config:
    import: optional:configserver:http://config-service:8071
  main:
    web-application-type: reactive

server:
  port: 8765
