version: '2'

services:

  config-service:
    container_name: config-service
    build: ./infrastructure/config-service
    ports:
      - "8071:8071"
    networks:
      - spring-cloud-network

  discovery-service:
    container_name: discovery-service
    build: ./infrastructure/discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge