spring:
  application:
    name: domain-service
  cloud:
    config:
      enabled: true
      uri: http://config-server:8071
  config:
    import: optional:configserver:http://config-service:8071

server:
  port: 8011
