spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kyrortnik/config-server.git
          default-label: main

server:
  port: 8071
